// @octokit/plugin-rest-endpoint-methods

module.exports = {
  users: {
    addEmailForAuthenticated: ['POST /user/emails'],
    block: ['PUT /user/blocks/{username}'],
    checkBlocked: ['GET /user/blocks/{username}'],
    checkFollowingForUser: ['GET /users/{username}/following/{target_user}'],
    checkPersonIsFollowedByAuthenticated: ['GET /user/following/{username}'],
    createGpgKeyForAuthenticated: ['POST /user/gpg_keys'],
    createPublicSshKeyForAuthenticated: ['POST /user/keys'],
    deleteEmailForAuthenticated: ['DELETE /user/emails'],
    deleteGpgKeyForAuthenticated: ['DELETE /user/gpg_keys/{gpg_key_id}'],
    deletePublicSshKeyForAuthenticated: ['DELETE /user/keys/{key_id}'],
    follow: ['PUT /user/following/{username}'],
    getAuthenticated: ['GET /user'],
    getByUsername: ['GET /users/{username}'],
    getContextForUser: ['GET /users/{username}/hovercard'],
    getGpgKeyForAuthenticated: ['GET /user/gpg_keys/{gpg_key_id}'],
    getPublicSshKeyForAuthenticated: ['GET /user/keys/{key_id}'],
    list: ['GET /users'],
    listBlockedByAuthenticated: ['GET /user/blocks'],
    listEmailsForAuthenticated: ['GET /user/emails'],
    listFollowedByAuthenticated: ['GET /user/following'],
    listFollowersForAuthenticatedUser: ['GET /user/followers'],
    listFollowersForUser: ['GET /users/{username}/followers'],
    listFollowingForUser: ['GET /users/{username}/following'],
    listGpgKeysForAuthenticated: ['GET /user/gpg_keys'],
    listGpgKeysForUser: ['GET /users/{username}/gpg_keys'],
    listPublicEmailsForAuthenticated: ['GET /user/public_emails'],
    listPublicKeysForUser: ['GET /users/{username}/keys'],
    listPublicSshKeysForAuthenticated: ['GET /user/keys'],
    setPrimaryEmailVisibilityForAuthenticated: ['PATCH /user/email/visibility'],
    unblock: ['DELETE /user/blocks/{username}'],
    unfollow: ['DELETE /user/following/{username}'],
    updateAuthenticated: ['PATCH /user'],
  },
}
